apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: university-bets
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: university_bets
  POSTGRES_DB: university_bets
  JWT_EXPIRATION: "86400000"
  CORS_ORIGINS: "http://localhost,http://localhost:3000"
