apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: university-bets
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  JWT_SECRET: mySecretKeyForJwtTokenGenerationAndValidation123456789
